### ISSUE TITLE
plugin causes a crash

### ISSUE THREAD

**Issue by pvojnisek** [uphy/joplin-plantuml-plugin#3]
If you paste this code into the editor, the editor will crash. Take care because you will not be able to reopen the Joplin notebook anymore!
The example is from here: https://plantuml.com/salt

```
@startsalt
{+
{* File | Edit | Source | Refactor }
{/ General | Fullscreen | Behavior | Saving }
{
{ Open image in: | ^Smart Mode^ }
[X] Smooth images when zoomed
[X] Confirm image deletion
[ ] Show hidden images
}
[Close]
}
@endsalt
```

Joplin sends this error message:

```
Error
Joplin encountered a fatal error and could not continue. To report the error, please copy the *entire content* of this page and post it on Joplin forum or GitHub.

Message
Version info
Joplin for Desktop

Copyright © 2016-2021 Laurent Cozic
Joplin 1.7.11 (prod, linux)

Client ID: 17c149a0a4094fbea7714d83bbecd8ad
Sync Version: 2
Profile Version: 34
Keychain Supported: No
Component stack

    in NoteEditor (created by Connect(NoteEditor))
    in Connect(NoteEditor) (created by ResizableLayout)
    in div (created by styled.div)
    in styled.div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in div (created by ResizableLayout)
    in ResizableLayout (created by MainScreenComponent)
    in div (created by MainScreenComponent)
    in MainScreenComponent (created by Connect(MainScreenComponent))
    in Connect(MainScreenComponent) (created by NavigatorComponent)
    in div (created by NavigatorComponent)
    in NavigatorComponent (created by Connect(NavigatorComponent))
    in Connect(NavigatorComponent) (created by RootComponent)
    in ThemeProvider (created by RootComponent)
    in StyleSheetManager (created by RootComponent)
    in RootComponent (created by Connect(RootComponent))
    in Connect(RootComponent)
    in ErrorBoundary
    in Provider
```

**Comment by akadaedalus** [comment]
I just came across this bug.  The PR fixes it, please publish a new version.  I wasn't thrilled about having to pull the code and install webpack to build/update.

The resulting plantuml graphic came out nicely though, good work there.

**Comment by ocelotsloth** [comment]
@uphy could you work with @laurent22 to publish a new version including #4? The current guidance upstream is that we wait for a release (https://github.com/laurent22/joplin/issues/4843#issuecomment-820261548).

I've also encountered this crash.

**Comment by msbentley** [comment]
Probably this is the same issue as when trying to use json in plantuml? I raised this issue on joplin and the application should no longer crash after this fix is merged/released: https://github.com/laurent22/joplin/issues/5273.

If this is not the same, I can raise a separate issue.

**Comment by laurent22** [comment]
Just to be clear, the app will no longer crash but the bug in the plugin or PlantUML lib is still present. I think the issue might with the wrapped markdown-it plugin which throws errors instead of handling parsing errors gracefully.

**Comment by msbentley** [comment]
Thanks @laurent22 - yes, I did a very bad job of explaining that the crash would not happen, but that the bug was still there!!
